export const US_CITY_BATCH = [
  { city: "Nashville", state: "Tennessee" },
  { city: "Oklahoma City", state: "Oklahoma" },
  { city: "El Paso", state: "Texas" },
  { city: "Boston", state: "Massachusetts" },
  { city: "Portland", state: "Oregon" },
  { city: "Las Vegas", state: "Nevada" },
  { city: "Detroit", state: "Michigan" },
  { city: "Memphis", state: "Tennessee" },
  { city: "Louisville", state: "Kentucky" },
  { city: "Baltimore", state: "Maryland" },
  { city: "Milwaukee", state: "Wisconsin" },
  { city: "Albuquerque", state: "New Mexico" },
  { city: "Tucson", state: "Arizona" },
  { city: "Fresno", state: "California" },
  { city: "Sacramento", state: "California" },
  { city: "Atlanta", state: "Georgia" },
  { city: "Kansas City", state: "Missouri" },
  { city: "Mesa", state: "Arizona" },
  { city: "Raleigh", state: "North Carolina" },
  { city: "Colorado Springs", state: "Colorado" },
  { city: "Omaha", state: "Nebraska" },
  { city: "Miami", state: "Florida" },
  { city: "Virginia Beach", state: "Virginia" },
  { city: "Oakland", state: "California" },
  { city: "Minneapolis", state: "Minnesota" },
  { city: "Tulsa", state: "Oklahoma" },
  { city: "Bakersfield", state: "California" },
  { city: "Wichita", state: "Kansas" },
  { city: "Arlington", state: "Texas" },
  { city: "Aurora", state: "Colorado" },
  { city: "Tampa", state: "Florida" },
  { city: "New Orleans", state: "Louisiana" },
  { city: "Cleveland", state: "Ohio" },
  { city: "Honolulu", state: "Hawaii" },
  { city: "Anaheim", state: "California" },
  { city: "Lexington", state: "Kentucky" },
  { city: "Stockton", state: "California" },
  { city: "Corpus Christi", state: "Texas" },
  { city: "Henderson", state: "Nevada" },
  { city: "Riverside", state: "California" },
  { city: "Newark", state: "New Jersey" },
  { city: "Saint Paul", state: "Minnesota" },
  { city: "Santa Ana", state: "California" },
  { city: "Cincinnati", state: "Ohio" },
  { city: "Irvine", state: "California" },
  { city: "Orlando", state: "Florida" },
  { city: "Pittsburgh", state: "Pennsylvania" },
  { city: "St. Louis", state: "Missouri" },
  { city: "Greensboro", state: "North Carolina" },
  { city: "Jersey City", state: "New Jersey" },
  { city: "Anchorage", state: "Alaska" },
  { city: "Lincoln", state: "Nebraska" },
  { city: "Plano", state: "Texas" },
  { city: "Durham", state: "North Carolina" },
  { city: "Buffalo", state: "New York" },
  { city: "Chandler", state: "Arizona" },
  { city: "Chula Vista", state: "California" },
  { city: "Toledo", state: "Ohio" },
  { city: "Madison", state: "Wisconsin" },
  { city: "Gilbert", state: "Arizona" },
  { city: "Reno", state: "Nevada" },
  { city: "Fort Wayne", state: "Indiana" },
  { city: "North Las Vegas", state: "Nevada" },
  { city: "St. Petersburg", state: "Florida" },
  { city: "Lubbock", state: "Texas" },
  { city: "Irving", state: "Texas" },
  { city: "Laredo", state: "Texas" },
  { city: "Winston-Salem", state: "North Carolina" },
  { city: "Chesapeake", state: "Virginia" },
  { city: "Glendale", state: "Arizona" },
  { city: "Garland", state: "Texas" },
  { city: "Scottsdale", state: "Arizona" },
  { city: "Boise", state: "Idaho" },
  { city: "Norfolk", state: "Virginia" },
  { city: "Fremont", state: "California" },
  { city: "Spokane", state: "Washington" },
  { city: "Santa Clarita", state: "California" },
  { city: "Tacoma", state: "Washington" },
  { city: "Hialeah", state: "Florida" },
  { city: "San Bernardino", state: "California" },
  { city: "Modesto", state: "California" },
] as const;
